locale: "ja"
local_backend: true
backend:
  name: github
  repo: iU-Alumni-Association/i-u-io
  branch: main
  site_domain: https://test.i-u.io
  base_url: https://test.i-u.io
  auth_endpoint: /api/auth
media_folder: static/images
public_folder: /images
collections:
  - name: 'events'
    label: 'イベント'
    folder: 'content/events'
    create: true
    slug: '{{slug}}'
    fields:
    - { label: 'タイトル', name: 'title', widget: 'string', required: true }
    - { label: '公開日時', name: 'date', widget: 'datetime', required: true }
    - { label: '説明', name: 'description', widget: 'text', required: false }
    - { label: '本文', name: 'body', widget: 'markdown', required: true }
    - { label: 'タグ', name: 'tags', widget: 'list', default: [], required: false }
    - { label: 'カテゴリー', name: 'categories', widget: 'list', default: [], required: false }
    - { label: 'お気に入り', name: 'favorite', widget: 'boolean', default: false, required: false }

  - name: 'circle'
    label: 'サークル情報'
    folder: 'content/circle'
    create: true
    slug: '{{slug}}'
    fields:
    - { label: 'タイトル', name: 'title', widget: 'string', required: true }
    - { label: '公開日時', name: 'date', widget: 'datetime', required: true }
    - { label: '説明', name: 'description', widget: 'text', required: false }
    - { label: '本文', name: 'body', widget: 'markdown', required: true }
    - { label: 'タグ', name: 'tags', widget: 'list', default: [], required: false }
    - { label: 'カテゴリー', name: 'categories', widget: 'list', default: [], required: false }
    - { label: 'お気に入り', name: 'favorite', widget: 'boolean', default: false, required: false }

  - name: 'news'
    label: 'ニュース'
    folder: 'content/news'
    create: true
    slug: '{{slug}}'
    fields:
    - { label: 'タイトル', name: 'title', widget: 'string', required: true }
    - { label: '公開日時', name: 'date', widget: 'datetime', required: true }
    - { label: '説明', name: 'description', widget: 'text', required: false }
    - { label: '本文', name: 'body', widget: 'markdown', required: true }
    - { label: 'タグ', name: 'tags', widget: 'list', default: [], required: false }
    - { label: 'カテゴリー', name: 'categories', widget: 'list', default: [], required: false }
    - { label: 'お気に入り', name: 'favorite', widget: 'boolean', default: false, required: false }

  - name: 'column'
    label: '自治委員会コラム'
    folder: 'content/column'
    create: true
    slug: '{{slug}}'
    fields:
    - { label: 'タイトル', name: 'title', widget: 'string', required: true }
    - { label: '公開日時', name: 'date', widget: 'datetime', required: true }
    - { label: '説明', name: 'description', widget: 'text', required: false }
    - { label: '本文', name: 'body', widget: 'markdown', required: true }
    - { label: 'タグ', name: 'tags', widget: 'list', default: [], required: false }
    - { label: 'カテゴリー', name: 'categories', widget: 'list', default: [], required: false }
    - { label: 'お気に入り', name: 'favorite', widget: 'boolean', default: false, required: false }

  - name: 'legal'
    label: 'Legal'
    folder: 'content/legal'
    create: false
    slug: '{{slug}}'
    fields:
    - { label: 'タイトル', name: 'title', widget: 'string', required: true }
    - { label: '公開日時', name: 'date', widget: 'datetime', required: true }
    - { label: '説明', name: 'description', widget: 'text', required: false }
    - { label: '本文', name: 'body', widget: 'markdown', required: true }

  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: false
    fields:
    - { label: 'タイトル', name: 'title', widget: 'string', required: true }
    - { label: '説明', name: 'description', widget: 'text', required: false }
    - { label: '本文', name: 'body', widget: 'markdown', required: true }
