locale: "ja"
local_backend: true
backend:
  name: github
  repo: iU-Alumni-Association/i-u-io
  branch: main
  site_domain: https://i-u.io
  base_url: https://i-u.io
  auth_endpoint: /api/auth
  show_preview_links: true
media_folder: static/images
public_folder: /images
collections:
  - name: "index"
    label: "Indexページ"
    files:
      - label: "トップページ"
        name: "index"
        file: "content/_index.md"
        fields:
          - {
              label: "説明",
              name: "description",
              widget: "text",
              required: false,
            }
          - { label: "本文", name: "body", widget: "markdown", required: true }

  - name: "events"
    label: "イベント"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    preview_path: "{{slug}}"
    editor:
      preview: true
    fields:
      - {
          label: "画像",
          name: "image",
          widget: "image",
          required: false,
          media_library: { allow_multiple: false },
        }
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日時", name: "date", widget: "datetime", required: false }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }
      - {
          label: "タグ",
          name: "tags",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "カテゴリー",
          name: "categories",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "お気に入り",
          name: "favorite",
          widget: "boolean",
          default: false,
          required: false,
        }

  - name: "circle"
    label: "サークル情報"
    folder: "content/circle"
    create: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    editor:
      preview: true
    fields:
      - {
          label: "画像",
          name: "image",
          widget: "image",
          required: false,
          media_library: { allow_multiple: false },
        }
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日時", name: "date", widget: "datetime", required: false }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }
      - {
          label: "タグ",
          name: "tags",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "カテゴリー",
          name: "categories",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "お気に入り",
          name: "favorite",
          widget: "boolean",
          default: false,
          required: false,
        }

  - name: "news"
    label: "ニュース"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    preview_path: "{{slug}}"
    editor:
      preview: true
    fields:
      - {
          label: "画像",
          name: "image",
          widget: "image",
          required: false,
          media_library: { allow_multiple: false },
        }
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日時", name: "date", widget: "datetime", required: false }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }
      - {
          label: "タグ",
          name: "tags",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "カテゴリー",
          name: "categories",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "お気に入り",
          name: "favorite",
          widget: "boolean",
          default: false,
          required: false,
        }

  - name: "column"
    label: "学友会コラム"
    folder: "content/column"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    preview_path: "{{slug}}"
    editor:
      preview: true
    fields:
      - {
          label: "画像",
          name: "image",
          widget: "image",
          required: false,
          media_library: { allow_multiple: false },
        }
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日時", name: "date", widget: "datetime", required: false }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }
      - {
          label: "タグ",
          name: "tags",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "カテゴリー",
          name: "categories",
          widget: "list",
          default: [],
          required: false,
        }
      - {
          label: "お気に入り",
          name: "favorite",
          widget: "boolean",
          default: false,
          required: false,
        }

  - name: "legal"
    label: "リーガル系"
    folder: "content/legal"
    create: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日時", name: "date", widget: "datetime", required: false }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }

  - name: "about"
    label: "組織情報"
    folder: "content/about"
    create: false
    preview_path: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }
